version: '3.5'

services:
  notion:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./app:/app:cached
    ports:
      - 9099:9099 # Auth
      - 4000:4000 # Emulator Suite UI
      - 5001:5001 # Cloud Functions
      - 8080:8080 # Cloud Firestore
    working_dir: /app
    tty: true

