name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: app/functions/package-lock.json
      - name: Install dependencies
        working-directory: ./app/functions
        run: npm install && npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
    env:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_LIFELOG_DATABASE_ID: ${{ secrets.NOTION_LIFELOG_DATABASE_ID }}
      NOTION_WATCHLIST_DATABASE_ID: ${{ secrets.NOTION_WATCHLIST_DATABASE_ID }}
      NOTION_RESTRAUNT_DATABSE_ID: ${{ secrets.NOTION_RESTRAUNT_DATABSE_ID }}
      GOOGLE_MAP_TIMELINE_URL: ${{ secrets.GOOGLE_MAP_TIMELINE_URL }}
      GOOGLE_MAP_APIKEY: ${{ secrets.GOOGLE_MAP_APIKEY }}
      FIRESTORAGE_BUCKET: ${{ secrets.FIRESTORAGE_BUCKET }}
      PROJECT_PATH: ./app