name: Deploy

on:
  push:
    branches:
      - cicdtest

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: app/functions/package-lock.json
      - name: Install dependencies
        working-directory: ./app/functions
        run: npm install && npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v11.9.0
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          PROJECT_PATH: ./app

      # - name: Build
      #   working-directory: ./app/functions
      #   run: npm run-script build
      # - name: Install Firebase-tools
      #   working-directory: ./app/functions
      #   run: npm install -g firebase-tools
      # - name: Deploy to Firebase
      #   working-directory: ./app/functions
      #   run: firebase deploy --only functions --token $GCP_SA_KEY
      #   env:
      #     GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}