 name: Deploy

 on:
   push:
     branches:
       - cicdtest

 jobs:
   deploy:
     name: Deploy
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repo
         working-directory: ./app
         uses: actions/checkout@v3
       - name: Setup node
         working-directory: ./app
         uses: actions/setup-node@v3
         with:
           node-version: 16
           cache: "npm"
           cache-dependency-path: functions/package-lock.json
       - name: Install dependencies
         working-directory: ./app
         run: npm install
       - name: Deploy to Firebase
         working-directory: ./app
         run: firebase deploy --only functions
         env:
           GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
           CONFIG_VALUES: ${{ secrets.CONFIG_VALUES }}