 name: Deploy

 on:
   push:
     branches:
       - cicdtest

 jobs:
   deploy:
     name: Deploy
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repo
         uses: actions/checkout@v3
       - name: Setup node
         uses: actions/setup-node@v3
         with:
           node-version: 16
           cache: "npm"
           cache-dependency-path: app/functions/package-lock.json
       - name: Install dependencies
         working-directory: ./app/functions
         run: |
           npm install
           npm run build
       - name: Build
         working-directory: ./app/functions
         run: npm run-script build
       - name: Deploy to Firebase
         working-directory: ./app/functions
         run: firebase deploy --only functions
         env:
           GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
           CONFIG_VALUES: ${{ secrets.CONFIG_VALUES }}