name: Test

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: app/functions/package-lock.json
      - name: Install dependencies
        working-directory: ./app/functions
        run: npm install && npm run build
      - name: Make .env
        working-directory: ./app/functions
        run: echo "${{ secrets.TEST_CONFIG_VALUES }}" > .env.local
      - name: Test
        working-directory: ./app/functions
        run: npm test